# This is a CI Testing
name: CI-Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my-testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Hello
        run: echo "Hello WORLD from TESTING"
      
      - name: Install Newman
        run: npm install newman
      
      - name: Install Newman Reporter
        run: npm install newman-reporter-htmlextra
      
      - name: install newman-reporter-htmlextra
        run: npm install newman-reporter-htmlextra

      - name: List current folder
        run: ls -la
      
      - name: GIT CLONE my Repo
        uses: actions/checkout@v1
      
      - name: List current folder
        run: ls -la
      
      - name: Test API by NEWMAN
        run: newman run my-api-test-postman.postman_collection.json -r htmlextra --reporter-htmlextra-export ./results/report.html
  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    steps:
      - name: Print Hello
        run: echo "HEllO WORLD from DEPLOY"
    

